### PR TITLE
added  3 files

### PR DESCRIPTION
**Pull request by ymasaki99**
check files' contens

### CODE REVIEW

**Comment by jfunabashi99** [comment]
OK

**Comment by jfunabashi99** [comment]
Merged

**Comment by ymasaki99** [comment]
I'll merge

**Comment by ymasaki99** [comment]
I'll close

**Review by jfunabashi99 — COMMENTED** [review]
OK

**Review by jfunabashi99 — COMMENTED** [review]
OK

**Review by jfunabashi99 — COMMENTED** [review]
OK

**Review by jfunabashi99 — COMMENTED** [review]
OKOKOK

**Pull request closed without merging**
